-- Tier 3.1 Phase D — remove the RFC 8628 device-flow storage.
--
-- Background. With BSVibe-Auth#41 + the four product CLI cascade
-- (bsvibe-cli-base 0.2.0) shipped, every supported caller mints PATs
-- via the authorization_code + PKCE flow (RFC 7636 + RFC 8252). The
-- /api/oauth/device/* endpoints are gone in this same change and
-- `urn:ietf:params:oauth:grant-type:device_code` is removed from
-- `.well-known/oauth-authorization-server`'s grant_types_supported.
--
-- The `device_codes` table has no foreign keys into other public-schema
-- objects (`oauth_clients.client_id` is referenced FROM device_codes,
-- not TO it), so the DROP is safe — outstanding rows are abandoned but
-- they were single-use and TTL-bound (10 minutes) anyway. Any in-flight
-- approval at the moment of deploy fails with `Cannot POST /...` and
-- the CLI re-runs into the loopback path.
--
-- Renamed from 20260518_000002 → 20260520_000001 in a follow-up commit
-- because the supabase_migrations.schema_migrations PK uses only the
-- 8-char YYYYMMDD prefix; the original filename collided with the Phase B
-- migration 20260518_000001_cli_client_loopback_redirect_uris.sql
-- (see memory `supabase-migration-version-collision-silent-rollback`).
-- The corresponding _e2e mirror lands in Tier 3.1 Phase E at 20260519.

drop table if exists public.device_codes;
